import {Platform, StyleSheet} from 'react-native';

export const GameScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  checkBoxContainer: {
    flexDirection: 'row',
  },
  checkinside: {
    padding: 1,
    height: 14,
    width: 14,
    backgroundColor: 'rgb(85,124,230)',
    borderRadius: 2,
    borderWidth: 1,
    borderColor: 'rgb(85,124,230)',
  },
  checkICon: {
    top: 8,
    height: 20,
    width: 20,
    borderRadius: 2,
    borderWidth: 1,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: 'rgb(85,124,230)',
  },
  checkboxInputContainer: {padding: 0},
  checkboxLabel: {
    paddingStart: 20,
    top: 7,
    fontSize: 15,
    fontWeight: '600',
    color: 'black',
  },
  checkedboxLabel: {
    paddingStart: 20,
    top: 7,
    fontSize: 15,
    fontWeight: '600',
    color: 'rgb(85,124,230)',
  },
  checkboxRow: {
    flexDirection: 'row',
    marginBottom: 5,
    marginStart: 5,
  },
  radioIcon: {
    top: 8,
    height: 20,
    width: 20,
    borderRadius: 12.5,
    borderWidth: 1,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: 'rgb(85,124,230)',
  },
  checkboxLabelcheck: {
    paddingStart: 20,
    top: 7,
    fontSize: 15,
    fontWeight: '600',
    color: 'black',
  },
  checkedboxLabelcheck: {
    paddingStart: 20,
    top: 7,
    fontSize: 15,
    fontWeight: '600',
    color: 'rgb(85,124,230)',
  },
  radioiconinside: {
    padding: 1,
    height: 14,
    width: 14,
    backgroundColor: 'rgb(85,124,230)',
    borderRadius: 7,
    borderWidth: 1,
    borderColor: 'rgb(85,124,230)',
  },
  radioBtnRow: {
    flexDirection: 'row',
    margin: 5,
  },
  filterSubHeader: {color: 'black', fontWeight: '900', marginBottom: 5},
  filterInnerContainer: {padding: 10, minheight: 160},
  checkBoxOutercontainer: {paddingBottom: 10},
  checkBox: {
    height: 18,
    width: 18,
    borderColor: 'rgb(90,193,102)',
    borderWidth: 1,
    marginEnd: 10,
    bottom: -1,
  },
  filterBtn: {
    height: 50,
    margin: 10,
    width: 205,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgb(85,124,230)',
  },
  labelCheckbox: {
    fontWeight: 'bold',
    color: 'black',
    fontSize: Platform.OS === 'ios' ? 12 : 13,
  },
  gameCardContainer: {
    minHeight: 150,
    margin: 10,
    backgroundColor: 'white',
    padding: 10,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  filterText: {
    color: 'rgb(85,124,230)',
    fontSize: 18,
    marginStart: 10,
    fontWeight: 'bold',
  },
  innerDrawer: {
    backgroundColor: 'white',
    right: 0,
    top: 0,
    position: 'absolute',
    elevation: 10,
    zIndex: 10,
    height: '100%',
    width: 225,
  },
  closeText: {
    textAlign: 'right',
    fontWeight: 'bold',
    fontSize: 16,
  },
  closeBtn: {
    fontSize: 18,
    width: 105,
    height: 60,
    justifyContent: 'center',
    marginStart: 10,
    fontWeight: 'bold',
  },
  innerHeader: {
    width: 225,
    flexDirection: 'row',
    borderColor: 'white',
    borderBottomColor: 'rgb(85,124,230)',
    paddingHorizontal: 10,
    borderWidth: 0.7,
    height: 60,
    alignItems: 'center',
  },
  gameCardHeader: {
    paddingBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  gameCardTitle: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  description: {marginVertical: 10},
  searchBar: {
    color: 'black',
  },
  settingSvg: {
    position: 'absolute',
    right: 15,
    top: 4.5,
    zIndex: 1,
  },
  loadingText: {
    justifyContent: 'center',
    flexDirection: 'row',
  },
  searchInnerContainer: {
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginHorizontal: 15,
    marginBottom: 10,
    backgroundColor: 'rgba(85,124,230,0.2)',
    height: 40,
    borderRadius: 10,
    marginTop: 10,
    paddingHorizontal: 10,
    paddingEnd: 70,
  },
  drawerOuterContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    elevation: 9,
    zIndex: 9,
    backgroundColor: 'rgb(155,155,155)',
    width: '100%',
    height: '100%',
    opacity: 0.3,
  },
});
